# Generated by Django 5.1.4 on 2024-12-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_dislikes_post_likes_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='role',
            field=models.CharField(default='teacher', max_length=20),
        ),
    ]
