# Generated by Django 5.1.4 on 2024-12-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_disliked_by_post_liked_by_remove_post_dislikes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='role',
            field=models.CharField(default='teacher', max_length=20),
        ),
    ]
