# Generated by Django 5.1.4 on 2025-01-01 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_message_seen_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='roll_number',
        ),
    ]
