# Generated by Django 5.1.4 on 2025-01-01 14:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_rename_status_message_receiver_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_role', models.CharField(max_length=50)),
                ('receiver_role', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(max_length=100)),
                ('problem', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('sent_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_time', models.DateTimeField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('accepted_by', models.ManyToManyField(blank=True, related_name='emergency_accepted', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ManyToManyField(blank=True, related_name='emergency_rejected', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_resolved', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
