# Generated by Django 5.1.4 on 2025-01-03 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_rename_response_emergencymessage_reply_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencymessage',
            name='sent_to_user',
        ),
        migrations.AddField(
            model_name='emergencymessage',
            name='sent_to_user',
            field=models.ManyToManyField(related_name='emergency_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
