# Generated by Django 5.1.4 on 2025-01-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_remove_emergencymessage_sent_to_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofiledetails',
            name='image',
            field=models.URLField(blank=True, default='https:\\i.imgur.com\\7suwDp5.jpeg', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofiledetails',
            name='image',
            field=models.URLField(blank=True, default='https:\\i.imgur.com\\7suwDp5.jpeg', max_length=500, null=True),
        ),
    ]
