# Generated by Django 5.1.4 on 2025-01-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_teacherprofiledetails_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofiledetails',
            name='image',
            field=models.URLField(blank=True, default='https://i.imgur.com/7suwDp5.jpeg', max_length=500, null=True),
        ),
    ]
